// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: country.proto

// Protobuf Java Version: 3.25.2
package ProtocolBufferTest;

public final class CountryProto {
  private CountryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CountryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Country)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string capital = 2;</code>
     * @return The capital.
     */
    java.lang.String getCapital();
    /**
     * <code>string capital = 2;</code>
     * @return The bytes for capital.
     */
    com.google.protobuf.ByteString
        getCapitalBytes();

    /**
     * <code>int32 population = 3;</code>
     * @return The population.
     */
    int getPopulation();

    /**
     * <code>repeated string city = 4;</code>
     * @return A list containing the city.
     */
    java.util.List<java.lang.String>
        getCityList();
    /**
     * <code>repeated string city = 4;</code>
     * @return The count of city.
     */
    int getCityCount();
    /**
     * <code>repeated string city = 4;</code>
     * @param index The index of the element to return.
     * @return The city at the given index.
     */
    java.lang.String getCity(int index);
    /**
     * <code>repeated string city = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the city at the given index.
     */
    com.google.protobuf.ByteString
        getCityBytes(int index);

    /**
     * <code>.Country.HDI hdi = 5;</code>
     * @return The enum numeric value on the wire for hdi.
     */
    int getHdiValue();
    /**
     * <code>.Country.HDI hdi = 5;</code>
     * @return The hdi.
     */
    ProtocolBufferTest.CountryProto.Country.HDI getHdi();
  }
  /**
   * Protobuf type {@code Country}
   */
  public static final class Country extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Country)
      CountryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Country.newBuilder() to construct.
    private Country(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Country() {
      name_ = "";
      capital_ = "";
      city_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      hdi_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Country();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocolBufferTest.CountryProto.internal_static_Country_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocolBufferTest.CountryProto.internal_static_Country_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtocolBufferTest.CountryProto.Country.class, ProtocolBufferTest.CountryProto.Country.Builder.class);
    }

    /**
     * Protobuf enum {@code Country.HDI}
     */
    public enum HDI
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>VERY_HIGH = 0;</code>
       */
      VERY_HIGH(0),
      /**
       * <code>HIGH = 1;</code>
       */
      HIGH(1),
      /**
       * <code>MEDIUM = 2;</code>
       */
      MEDIUM(2),
      /**
       * <code>LOW = 3;</code>
       */
      LOW(3),
      /**
       * <code>VERY_LOW = 4;</code>
       */
      VERY_LOW(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>VERY_HIGH = 0;</code>
       */
      public static final int VERY_HIGH_VALUE = 0;
      /**
       * <code>HIGH = 1;</code>
       */
      public static final int HIGH_VALUE = 1;
      /**
       * <code>MEDIUM = 2;</code>
       */
      public static final int MEDIUM_VALUE = 2;
      /**
       * <code>LOW = 3;</code>
       */
      public static final int LOW_VALUE = 3;
      /**
       * <code>VERY_LOW = 4;</code>
       */
      public static final int VERY_LOW_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static HDI valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static HDI forNumber(int value) {
        switch (value) {
          case 0: return VERY_HIGH;
          case 1: return HIGH;
          case 2: return MEDIUM;
          case 3: return LOW;
          case 4: return VERY_LOW;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<HDI>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          HDI> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<HDI>() {
              public HDI findValueByNumber(int number) {
                return HDI.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ProtocolBufferTest.CountryProto.Country.getDescriptor().getEnumTypes().get(0);
      }

      private static final HDI[] VALUES = values();

      public static HDI valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private HDI(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Country.HDI)
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAPITAL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object capital_ = "";
    /**
     * <code>string capital = 2;</code>
     * @return The capital.
     */
    @java.lang.Override
    public java.lang.String getCapital() {
      java.lang.Object ref = capital_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        capital_ = s;
        return s;
      }
    }
    /**
     * <code>string capital = 2;</code>
     * @return The bytes for capital.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCapitalBytes() {
      java.lang.Object ref = capital_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        capital_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POPULATION_FIELD_NUMBER = 3;
    private int population_ = 0;
    /**
     * <code>int32 population = 3;</code>
     * @return The population.
     */
    @java.lang.Override
    public int getPopulation() {
      return population_;
    }

    public static final int CITY_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList city_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string city = 4;</code>
     * @return A list containing the city.
     */
    public com.google.protobuf.ProtocolStringList
        getCityList() {
      return city_;
    }
    /**
     * <code>repeated string city = 4;</code>
     * @return The count of city.
     */
    public int getCityCount() {
      return city_.size();
    }
    /**
     * <code>repeated string city = 4;</code>
     * @param index The index of the element to return.
     * @return The city at the given index.
     */
    public java.lang.String getCity(int index) {
      return city_.get(index);
    }
    /**
     * <code>repeated string city = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the city at the given index.
     */
    public com.google.protobuf.ByteString
        getCityBytes(int index) {
      return city_.getByteString(index);
    }

    public static final int HDI_FIELD_NUMBER = 5;
    private int hdi_ = 0;
    /**
     * <code>.Country.HDI hdi = 5;</code>
     * @return The enum numeric value on the wire for hdi.
     */
    @java.lang.Override public int getHdiValue() {
      return hdi_;
    }
    /**
     * <code>.Country.HDI hdi = 5;</code>
     * @return The hdi.
     */
    @java.lang.Override public ProtocolBufferTest.CountryProto.Country.HDI getHdi() {
      ProtocolBufferTest.CountryProto.Country.HDI result = ProtocolBufferTest.CountryProto.Country.HDI.forNumber(hdi_);
      return result == null ? ProtocolBufferTest.CountryProto.Country.HDI.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(capital_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, capital_);
      }
      if (population_ != 0) {
        output.writeInt32(3, population_);
      }
      for (int i = 0; i < city_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, city_.getRaw(i));
      }
      if (hdi_ != ProtocolBufferTest.CountryProto.Country.HDI.VERY_HIGH.getNumber()) {
        output.writeEnum(5, hdi_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(capital_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, capital_);
      }
      if (population_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, population_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < city_.size(); i++) {
          dataSize += computeStringSizeNoTag(city_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCityList().size();
      }
      if (hdi_ != ProtocolBufferTest.CountryProto.Country.HDI.VERY_HIGH.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, hdi_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtocolBufferTest.CountryProto.Country)) {
        return super.equals(obj);
      }
      ProtocolBufferTest.CountryProto.Country other = (ProtocolBufferTest.CountryProto.Country) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getCapital()
          .equals(other.getCapital())) return false;
      if (getPopulation()
          != other.getPopulation()) return false;
      if (!getCityList()
          .equals(other.getCityList())) return false;
      if (hdi_ != other.hdi_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CAPITAL_FIELD_NUMBER;
      hash = (53 * hash) + getCapital().hashCode();
      hash = (37 * hash) + POPULATION_FIELD_NUMBER;
      hash = (53 * hash) + getPopulation();
      if (getCityCount() > 0) {
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCityList().hashCode();
      }
      hash = (37 * hash) + HDI_FIELD_NUMBER;
      hash = (53 * hash) + hdi_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtocolBufferTest.CountryProto.Country parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtocolBufferTest.CountryProto.Country parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtocolBufferTest.CountryProto.Country parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtocolBufferTest.CountryProto.Country parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtocolBufferTest.CountryProto.Country parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtocolBufferTest.CountryProto.Country parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtocolBufferTest.CountryProto.Country parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtocolBufferTest.CountryProto.Country parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ProtocolBufferTest.CountryProto.Country parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ProtocolBufferTest.CountryProto.Country parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtocolBufferTest.CountryProto.Country parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtocolBufferTest.CountryProto.Country parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtocolBufferTest.CountryProto.Country prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Country}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Country)
        ProtocolBufferTest.CountryProto.CountryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtocolBufferTest.CountryProto.internal_static_Country_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtocolBufferTest.CountryProto.internal_static_Country_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtocolBufferTest.CountryProto.Country.class, ProtocolBufferTest.CountryProto.Country.Builder.class);
      }

      // Construct using ProtocolBufferTest.CountryProto.Country.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        capital_ = "";
        population_ = 0;
        city_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        hdi_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocolBufferTest.CountryProto.internal_static_Country_descriptor;
      }

      @java.lang.Override
      public ProtocolBufferTest.CountryProto.Country getDefaultInstanceForType() {
        return ProtocolBufferTest.CountryProto.Country.getDefaultInstance();
      }

      @java.lang.Override
      public ProtocolBufferTest.CountryProto.Country build() {
        ProtocolBufferTest.CountryProto.Country result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtocolBufferTest.CountryProto.Country buildPartial() {
        ProtocolBufferTest.CountryProto.Country result = new ProtocolBufferTest.CountryProto.Country(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ProtocolBufferTest.CountryProto.Country result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.capital_ = capital_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.population_ = population_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          city_.makeImmutable();
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.hdi_ = hdi_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocolBufferTest.CountryProto.Country) {
          return mergeFrom((ProtocolBufferTest.CountryProto.Country)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtocolBufferTest.CountryProto.Country other) {
        if (other == ProtocolBufferTest.CountryProto.Country.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCapital().isEmpty()) {
          capital_ = other.capital_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getPopulation() != 0) {
          setPopulation(other.getPopulation());
        }
        if (!other.city_.isEmpty()) {
          if (city_.isEmpty()) {
            city_ = other.city_;
            bitField0_ |= 0x00000008;
          } else {
            ensureCityIsMutable();
            city_.addAll(other.city_);
          }
          onChanged();
        }
        if (other.hdi_ != 0) {
          setHdiValue(other.getHdiValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                capital_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                population_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureCityIsMutable();
                city_.add(s);
                break;
              } // case 34
              case 40: {
                hdi_ = input.readEnum();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object capital_ = "";
      /**
       * <code>string capital = 2;</code>
       * @return The capital.
       */
      public java.lang.String getCapital() {
        java.lang.Object ref = capital_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          capital_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string capital = 2;</code>
       * @return The bytes for capital.
       */
      public com.google.protobuf.ByteString
          getCapitalBytes() {
        java.lang.Object ref = capital_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          capital_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string capital = 2;</code>
       * @param value The capital to set.
       * @return This builder for chaining.
       */
      public Builder setCapital(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        capital_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string capital = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCapital() {
        capital_ = getDefaultInstance().getCapital();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string capital = 2;</code>
       * @param value The bytes for capital to set.
       * @return This builder for chaining.
       */
      public Builder setCapitalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        capital_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int population_ ;
      /**
       * <code>int32 population = 3;</code>
       * @return The population.
       */
      @java.lang.Override
      public int getPopulation() {
        return population_;
      }
      /**
       * <code>int32 population = 3;</code>
       * @param value The population to set.
       * @return This builder for chaining.
       */
      public Builder setPopulation(int value) {

        population_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 population = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPopulation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        population_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList city_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCityIsMutable() {
        if (!city_.isModifiable()) {
          city_ = new com.google.protobuf.LazyStringArrayList(city_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string city = 4;</code>
       * @return A list containing the city.
       */
      public com.google.protobuf.ProtocolStringList
          getCityList() {
        city_.makeImmutable();
        return city_;
      }
      /**
       * <code>repeated string city = 4;</code>
       * @return The count of city.
       */
      public int getCityCount() {
        return city_.size();
      }
      /**
       * <code>repeated string city = 4;</code>
       * @param index The index of the element to return.
       * @return The city at the given index.
       */
      public java.lang.String getCity(int index) {
        return city_.get(index);
      }
      /**
       * <code>repeated string city = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the city at the given index.
       */
      public com.google.protobuf.ByteString
          getCityBytes(int index) {
        return city_.getByteString(index);
      }
      /**
       * <code>repeated string city = 4;</code>
       * @param index The index to set the value at.
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCityIsMutable();
        city_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string city = 4;</code>
       * @param value The city to add.
       * @return This builder for chaining.
       */
      public Builder addCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCityIsMutable();
        city_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string city = 4;</code>
       * @param values The city to add.
       * @return This builder for chaining.
       */
      public Builder addAllCity(
          java.lang.Iterable<java.lang.String> values) {
        ensureCityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, city_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string city = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string city = 4;</code>
       * @param value The bytes of the city to add.
       * @return This builder for chaining.
       */
      public Builder addCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCityIsMutable();
        city_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int hdi_ = 0;
      /**
       * <code>.Country.HDI hdi = 5;</code>
       * @return The enum numeric value on the wire for hdi.
       */
      @java.lang.Override public int getHdiValue() {
        return hdi_;
      }
      /**
       * <code>.Country.HDI hdi = 5;</code>
       * @param value The enum numeric value on the wire for hdi to set.
       * @return This builder for chaining.
       */
      public Builder setHdiValue(int value) {
        hdi_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.Country.HDI hdi = 5;</code>
       * @return The hdi.
       */
      @java.lang.Override
      public ProtocolBufferTest.CountryProto.Country.HDI getHdi() {
        ProtocolBufferTest.CountryProto.Country.HDI result = ProtocolBufferTest.CountryProto.Country.HDI.forNumber(hdi_);
        return result == null ? ProtocolBufferTest.CountryProto.Country.HDI.UNRECOGNIZED : result;
      }
      /**
       * <code>.Country.HDI hdi = 5;</code>
       * @param value The hdi to set.
       * @return This builder for chaining.
       */
      public Builder setHdi(ProtocolBufferTest.CountryProto.Country.HDI value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        hdi_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Country.HDI hdi = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHdi() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hdi_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Country)
    }

    // @@protoc_insertion_point(class_scope:Country)
    private static final ProtocolBufferTest.CountryProto.Country DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtocolBufferTest.CountryProto.Country();
    }

    public static ProtocolBufferTest.CountryProto.Country getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Country>
        PARSER = new com.google.protobuf.AbstractParser<Country>() {
      @java.lang.Override
      public Country parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Country> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Country> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtocolBufferTest.CountryProto.Country getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Country_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Country_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcountry.proto\"\250\001\n\007Country\022\014\n\004name\030\001 \001(" +
      "\t\022\017\n\007capital\030\002 \001(\t\022\022\n\npopulation\030\003 \001(\005\022\014" +
      "\n\004city\030\004 \003(\t\022\031\n\003hdi\030\005 \001(\0162\014.Country.HDI\"" +
      "A\n\003HDI\022\r\n\tVERY_HIGH\020\000\022\010\n\004HIGH\020\001\022\n\n\006MEDIU" +
      "M\020\002\022\007\n\003LOW\020\003\022\014\n\010VERY_LOW\020\004B\"\n\022ProtocolBu" +
      "fferTestB\014CountryProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Country_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Country_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Country_descriptor,
        new java.lang.String[] { "Name", "Capital", "Population", "City", "Hdi", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
