// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExampleService.proto

// Protobuf Java Version: 3.25.2
package com.example.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstname = 1;</code>
   * @return The firstname.
   */
  java.lang.String getFirstname();
  /**
   * <code>string firstname = 1;</code>
   * @return The bytes for firstname.
   */
  com.google.protobuf.ByteString
      getFirstnameBytes();

  /**
   * <code>string lastname = 2;</code>
   * @return The lastname.
   */
  java.lang.String getLastname();
  /**
   * <code>string lastname = 2;</code>
   * @return The bytes for lastname.
   */
  com.google.protobuf.ByteString
      getLastnameBytes();

  /**
   * <code>int64 age = 3;</code>
   * @return The age.
   */
  long getAge();

  /**
   * <code>repeated string hobbies = 4;</code>
   * @return A list containing the hobbies.
   */
  java.util.List<java.lang.String>
      getHobbiesList();
  /**
   * <code>repeated string hobbies = 4;</code>
   * @return The count of hobbies.
   */
  int getHobbiesCount();
  /**
   * <code>repeated string hobbies = 4;</code>
   * @param index The index of the element to return.
   * @return The hobbies at the given index.
   */
  java.lang.String getHobbies(int index);
  /**
   * <code>repeated string hobbies = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the hobbies at the given index.
   */
  com.google.protobuf.ByteString
      getHobbiesBytes(int index);

  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 5;</code>
   */
  int getBagOfTricksCount();
  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 5;</code>
   */
  boolean containsBagOfTricks(
      java.lang.String key);
  /**
   * Use {@link #getBagOfTricksMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getBagOfTricks();
  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getBagOfTricksMap();
  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 5;</code>
   */
  /* nullable */
java.lang.String getBagOfTricksOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; bagOfTricks = 5;</code>
   */
  java.lang.String getBagOfTricksOrThrow(
      java.lang.String key);

  /**
   * <code>.com.example.grpc.Sentiment sentiment = 6;</code>
   * @return The enum numeric value on the wire for sentiment.
   */
  int getSentimentValue();
  /**
   * <code>.com.example.grpc.Sentiment sentiment = 6;</code>
   * @return The sentiment.
   */
  com.example.grpc.Sentiment getSentiment();
}
